#!/usr/bin/env bash

# echo "Checking for SSH key, generating one if it doesn't exist ..."
#   [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

# echo "Copying public key to clipboard. Paste it into your Github account ..."
#   [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
#   open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  brew doctor
  brew update

echo "Installing Memcached...."
 brew install memcached

echo "Installing Redis, a good key-value database ..."
  brew install redis

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing freetds"
	brew install freetds

echo "Installing wget ..."
	brew install wget

echo "Installing oh-my-zsh"
	curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

echo "Installing RBEnv ..."
 	brew install rbenv
	echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
	echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
	exec $SHELL
	brew install ruby-build


echo "Installing Ruby"
	bash < <(curl -s https://raw.github.com/lorgio/laptop/master/ruby)

echo "Installing Applications"
	bash < <(curl -s https://raw.github.com/lorgio/laptop/master/applications)

echo "Installing code-repos"
	bash < <(curl -s https://raw.github.com/lorgio/laptop/master/code-repos)
